/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/



#include <stdio.h>
#include <string.h>

char findTheDifference(char* s, char* t) {
	int a = 0 , b = 0;
	for(int i = 0 ; i < strlen(s) ; i++){
		a += (int)s[i];
	}
	for(int i = 0 ; i < strlen(t) ; i++){
		b += (int)t[i];
	}
	return (char)(b-a);
}
int main(){
	printf("Added letter is : %c" , findTheDifference("" , "y"));
}c
